CREATE TABLE pedidos (
                         id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         cliente VARCHAR2(255 CHAR) NOT NULL,
                         valor NUMBER(19, 2) NOT NULL,
                         transacao_id VARCHAR2(255 CHAR),
                         idempotency_key VARCHAR2(255 CHAR),
                         status VARCHAR2(50 CHAR)
);

CREATE TABLE outbox_event (
                              id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              aggregate_type VARCHAR2(255 CHAR) NOT NULL,
                              aggregate_id VARCHAR2(255 CHAR) NOT NULL,
                              event_type VARCHAR2(255 CHAR) NOT NULL,
                              payload CLOB NOT NULL,
                              status VARCHAR2(50 CHAR) NOT NULL,
                              created_at TIMESTAMP NOT NULL,
                              processed_at TIMESTAMP
);

CREATE TABLE audit_log (
                           id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           action VARCHAR2(255 CHAR) NOT NULL,
                           entity_id VARCHAR2(255 CHAR),
                           details CLOB
);

CREATE TABLE conta (
                       id NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       titular VARCHAR2(255 CHAR),
                       saldo NUMBER(19, 2)
);

CREATE INDEX idx_outbox_status ON outbox_event(status);
